apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
  namespace: tech-support
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: tech-support
spec:
  replicas: 1

  selector:
    matchLabels:
      app: keycloak

  template:
    metadata:
      labels:
        app: keycloak

    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.7.1

          args:
            - start-dev
            - --import-realm

          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 9000

          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_ADMIN

            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_ADMIN_PASSWORD

            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: OIDC_CLIENT_SECRET

            - name: KC_HOSTNAME
              value: "https://auth.88-218-67-241.sslip.io"

            - name: KC_PROXY_HEADERS
              value: "xforwarded"

            - name: KC_HTTP_ENABLED
              value: "true"

            - name: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
              value: "true"

            - name: KC_HEALTH_ENABLED
              value: "true"

          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data

            - name: realm-config
              mountPath: /opt/keycloak/data/import/tech-support-realm.json
              subPath: tech-support-realm.json
              readOnly: true

          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12

          resources:
            requests:
              cpu: "200m"
              memory: "600Mi"
            limits:
              cpu: "800m"
              memory: "800Mi"

      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-pvc

        - name: realm-config
          configMap:
            name: keycloak-realm

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: tech-support
spec:
  type: ClusterIP

  selector:
    app: keycloak

  ports:
    - name: http
      port: 8080
      targetPort: 8080

    - name: management
      port: 9000
      targetPort: 9000
