apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: tech-support

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: tech-support-frontend:k8s
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3

          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "300m"
              memory: "150Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: tech-support

spec:
  type: ClusterIP

  selector:
    app: frontend

  ports:
    - port: 80
      targetPort: 80
