apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: tech-support
data:
  SPRING_PROFILES_ACTIVE: "oidc"
  DB_URL: "jdbc:postgresql://postgres:5432/ticketdb"
  POSTGRES_DB: "ticketdb"
  OIDC_CLIENT_ID: "tech-support-ticket-service"
  OIDC_ISSUER_URI: "https://auth.88-218-67-241.sslip.io/realms/tech-support"
  FRONTEND_URL: "https://88-218-67-241.sslip.io"
  SERVER_FORWARD_HEADERS_STRATEGY: "framework"
